api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPersonUtil.java
https://issues.openmrs.org/browse/FM-52
=> FamilyNamePrefix should be set as a Prefix, not as a Suffix FM52

api/src/main/java/org/openmrs/module/fhir/api/PersonService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/PersonServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPersonUtil.java, api/src/test/java/org/openmrs/module/fhir/api/PersonServiceTest.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPersonResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRPersonResource.java
* Add features for users to search for and retrieve one or many person resources
* Fixed issue in FHIRPersonUtil.generatePerson() method
* Added test cases for searchPersonsByName() method
=> Implemented Search by Name

api/src/main/java/org/openmrs/module/fhir/api/PersonService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/PersonServiceImpl.java, api/src/test/java/org/openmrs/module/fhir/api/PersonServiceTest.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPersonResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRPersonResource.java
* Added test cases for java API
=> Implemented search persons by name, birth year and gender

api/src/main/java/org/openmrs/module/fhir/api/ObsService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/ObsServiceImpl.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulObservationResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRObservationResource.java
* Implemented search for observations by dynamic chain parameter of patient identifier
TODO: Add test cases for Java API (Not found appropiate sample test data in openmrs-core).
@surangak  please review this pull request and provide appropriate improvements.
=> FM-53 Implemented search for Observations by a patient identifier

.gitignore, api/src/main/java/org/openmrs/module/fhir/api/EncounterService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/EncounterServiceImpl.java, api/src/test/java/org/openmrs/module/fhir/api/EncounterServiceTest.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulEncounterResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIREncounterResource.java
@surangak please review this pull request.
=> FM-15 Add chained parameters to search for Encounters by a patient identifier

omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPersonResourceProvider.java
The date.getYear() method return the value of year minus 1900.
E.g. If the year is 1971, then it returns 71 (1971-1900)
=> Fixed issue: Unable to search persons

api/src/main/java/org/openmrs/module/fhir/api/EncounterService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/EncounterServiceImpl.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulEncounterResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIREncounterResource.java
JIRA Issue : https://issues.openmrs.org/browse/FM-75
=> FM-75 : Add support to retire OpenMRS Encounters using FHIR

api/src/main/java/org/openmrs/module/fhir/api/PatientService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/PatientServiceImpl.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPatientResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRPatientResource.java
JIRA issue : https://issues.openmrs.org/browse/FM-73
=> FM-73 : Add support to retire OpenMRS Patients using FHIR

api/src/main/java/org/openmrs/module/fhir/api/PersonService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/PersonServiceImpl.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPersonResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRPersonResource.java
https://issues.openmrs.org/browse/FM-74
Please review
=> FM-74 Add support to retire OpenMRS Persons using FHIR

api/src/main/java/org/openmrs/module/fhir/api/PersonService.java, api/src/test/java/org/openmrs/module/fhir/api/PersonServiceTest.java
https://issues.openmrs.org/browse/FM-74
Added some unit tests. But have no idea how to test cases for 'Performing this interaction on a resource that is already deleted has no effect' and ' OpenMRS API refuses to retire a Person'.
=> FM-74 unit test for retire person

omod/src/main/java/org/openmrs/module/fhir/resources/FHIRLocationResource.java
fixed issue
https://github.com/sashrika/openmrs-module-fhir/blob/master/omod/src/main/java/org/openmrs/module/fhir/resources/FHIRLocationResource.java#L57
=> fixed a missing parantheses error

api/src/main/java/org/openmrs/module/fhir/api/ObsService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/ObsServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRObsUtil.java, api/src/test/java/org/openmrs/module/fhir/api/ObsServiceTest.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulObservationResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRObservationResource.java
FM-104
Please close the pull request 62
=> create obs with unit test

api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPractitionerUtil.java, api/src/test/java/org/openmrs/module/fhir/api/PractitionerServiceTest.java
https://issues.openmrs.org/browse/FM-112
added test for create pract. fixed a bug in the existing code(which was written by me :) )
=> test method for create practitioner

api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/DiagnosticReportHandler.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/DefaultDiagnosticReportHandler.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/RadiologyHandler.java, api/src/main/java/org/openmrs/module/fhir/api/impl/DiagnosticReportServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRDiagnosticReportUtil.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulDiagnosticReportResourceProvider.java
It'll retrieve all required filed for Diagnostic Report.
@surangak @harsha89 plz, review the code!
=> Implemented get existing Diagnostic Report

api/src/main/java/org/openmrs/module/fhir/api/util/FHIRConstants.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRObsUtil.java
Implemented HL7_ABBREVATION = "ST" support
https://issues.openmrs.org/browse/FM-104
=> concepts with ST data type

api/src/main/java/org/openmrs/module/fhir/api/DiagnosticReportService.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/DiagnosticReportHandler.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/DefaultDiagnosticReportHandler.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/RadiologyHandler.java, api/src/main/java/org/openmrs/module/fhir/api/impl/DiagnosticReportServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRDiagnosticReportUtil.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulDiagnosticReportResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRDiagnosticReportResource.java
@surangak @harsha89 Implemented [Retire existing Diagnostic Report](https://issues.openmrs.org/browse/FM-162).
Please, review the code.
=> Implemented retire DiagnosticReport (Encounter)

api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRUtils.java, omod/src/main/resources/config.xml
@harsha89 @surangak Please, review the code!.
=> FM 160 - Removed Hard Coded Uuid value to Global Props

api/src/main/java/org/openmrs/module/fhir/api/DiagnosticReportService.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/DiagnosticReportHandler.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/DefaultDiagnosticReportHandler.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/RadiologyHandler.java, api/src/main/java/org/openmrs/module/fhir/api/impl/DiagnosticReportServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRDiagnosticReportUtil.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulDiagnosticReportResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRDiagnosticReportResource.java
Currently working fileds are
* issued
* subject
* performer
* serviceCategory
=> FM-163 : Updating existing FHIR Diagnostic Report

api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRConstants.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRUtils.java, omod/src/main/resources/config.xml
@harsha89 @surangak Please, review the code!.
=> FM-164 Store persentedForm field using Binary data handler

api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java
This is fixed with issue on [FM-164](https://issues.openmrs.org/browse/FM-164). Refactor few codes here.
@surangak @harsha89 Please, review and merge this request.
=> FM-165 : Refactor Previous implemetation

api/src/main/java/org/openmrs/module/fhir/api/impl/ObsServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRObsUtil.java, api/src/test/java/org/openmrs/module/fhir/api/ObsServiceTest.java
https://issues.openmrs.org/browse/FM-106
=> error management for create obs

api/src/main/java/org/openmrs/module/fhir/api/impl/PersonServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPersonUtil.java
https://issues.openmrs.org/browse/FM-91
=> error managemnt for person

api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulDiagnosticReportResourceProvider.java
@surangak @harsha89 Please, review the code.
Is it necessary to include `result` in the `contained` field ? [See here](https://github.com/milankarunarathne/openmrs-module-fhir/blob/9b3e5bb6df0b4d4e16cc99718b22df6193819e3c/api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java#L106-L107)
=> FM-167 Store result field using Observations

api/src/main/java/org/openmrs/module/fhir/api/impl/PatientServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPatientUtil.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPatientResourceProvider.java
https://issues.openmrs.org/browse/FM-91
Initial commit
=> error management for patient

omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPersonResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRPersonResource.java
https://issues.openmrs.org/browse/FM-87
=> conditional update for person by name

omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPatientResourceProvider.java
https://issues.openmrs.org/browse/FM-94
=> conditional update by patient identifier

api/src/main/java/org/openmrs/module/fhir/api/util/FHIRConstants.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPatientResourceProvider.java
https://issues.openmrs.org/browse/FM-94
=> conditional update by name

api/src/main/java/org/openmrs/module/fhir/api/LocationService.java, api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java, api/src/main/java/org/openmrs/module/fhir/api/impl/LocationServiceImpl.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulLocationResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRLocationResource.java
https://issues.openmrs.org/browse/FM-101
please close the pull request https://github.com/openmrs/openmrs-module-fhir/pull/89
=> conditional update location by name, addressed git hub comments

api/src/main/java/org/openmrs/module/fhir/api/impl/PractitionerServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRConstants.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPractitionerUtil.java
removed hard coded values
https://issues.openmrs.org/browse/FM-116
=> removed hard coded values from practitioner update

omod/src/main/java/org/openmrs/module/fhir/server/FHIRRESTServer.java
please kill
https://github.com/openmrs/openmrs-module-fhir/pull/94. 
and
https://github.com/openmrs/openmrs-module-fhir/pull/92
=> added interceptors with hapi 1.1 version

api/src/main/java/org/openmrs/module/fhir/api/util/FHIRObsUtil.java
Set  the obs to the encounter null checking
=> set encounter null check

api/src/main/java/org/openmrs/module/fhir/api/EncounterService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/EncounterServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIREncounterUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/OMRSFHIRVisitUtil.java, api/src/test/java/org/openmrs/module/fhir/api/EncounterServiceTest.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulEncounterResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIREncounterResource.java
https://issues.openmrs.org/browse/FM-128 
Few other use cases needs to addressed
=> create encounter - initial commit

api/src/main/java/org/openmrs/module/fhir/api/PatientService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/PatientServiceImpl.java, api/src/test/java/org/openmrs/module/fhir/api/PatientServiceTest.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPatientResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRPatientResource.java
https://issues.openmrs.org/browse/FM-177
=> search patient by name will return a Bundle. Updated test cases

api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java
Implemented update `PresentedForm` field in LaboratoryHandler
E.g. in case the old report had 5 obs, and the new one had maybe 3 and didnt know which were getting replace without a clear identifier.
This implementation replace all the old five, and add the 3 new ones.
@surangak @harsha89 please, review this MR.
=> FM-169 Update presentedForm field using Binary Data Handler

api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/LaboratoryHandler.java
- Remove existing Result Fields and insert new Result as a Obs Group
@surangak @harsha89 please, review the code!
=> FM-170 Update result field using OpenMRS Obs

api/src/main/java/org/openmrs/module/fhir/api/impl/LocationServiceImpl.java, api/src/test/java/org/openmrs/module/fhir/api/LocationServiceTest.java
[https://issues.openmrs.org/browse/FM-176](url)
=> fixing location search 

api/src/main/java/org/openmrs/module/fhir/api/util/FHIRObsUtil.java, api/src/test/java/org/openmrs/module/fhir/api/EncounterServiceTest.java, api/src/test/java/org/openmrs/module/fhir/api/ObsServiceTest.java, api/src/test/java/org/openmrs/module/fhir/api/PatientServiceTest.java, api/src/test/java/org/openmrs/module/fhir/api/PersonServiceTest.java, omod/src/main/resources/config.xml, pom.xml
=> Support obs.interpretation and obs.status for openmrs-core 2.1.0+ -

api/src/main/java/org/openmrs/module/fhir/api/impl/MedicationRequestServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRMedicationRequestUtil.java, api/src/test/java/org/openmrs/module/fhir/api/MedicationRequestTest.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulPractitionerResourceProvider.java
OpenMRS not support drug order update
=> update medication request

api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/RadiologyHandler.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRRESTfulGenericClient.java, omod/pom.xml, omod/src/main/java/org/openmrs/module/fhir/server/FHIRRESTServer.java, omod/src/test/java/org/openmrs/module/fhir/omod/SwaggerDocumentGenerationTestCase.java, pom.xml
Issue : https://issues.openmrs.org/projects/FM/issues/FM-245
=> FM-245 Upgrading HAPI FHIR Library version

omod/src/main/java/org/openmrs/module/fhir/swagger/codegen/SwaggerCodeGenerator.java, omod/src/test/java/org/openmrs/module/fhir/omod/SwaggerSDKGenerationTestCase.java
JIRA Issue : https://issues.openmrs.org/browse/FM-246
=> FM-246 Add all language support and tests

api/src/main/resources/messages.properties, omod/src/main/webapp/apidocs.jsp
JIRA Issue : https://issues.openmrs.org/browse/FM-247
=> FM-247 Add Swagger SDK generation frontend implementation

omod/src/main/java/org/openmrs/module/fhir/swagger/SwaggerSpecificationCreator.java, omod/src/main/java/org/openmrs/module/fhir/swagger/docs/BasicAuth.java, omod/src/main/java/org/openmrs/module/fhir/swagger/docs/Security.java, omod/src/main/java/org/openmrs/module/fhir/swagger/docs/SecurityDefinitions.java, omod/src/main/java/org/openmrs/module/fhir/swagger/docs/SwaggerSpecification.java, omod/src/test/java/org/openmrs/module/fhir/omod/SwaggerDocumentGenerationTestCase.java
Issue - https://issues.openmrs.org/browse/FM-250
=> [FM-250] Add security definition section to swagger definition

api/src/main/java/org/openmrs/module/fhir/api/strategies/observation/ObservationStrategy.java, api/src/test/java/org/openmrs/module/fhir/api/ObsServiceTest.java
addresses this Jira ticket:
https://issues.openmrs.org/browse/FM-248
This is an updated and (hopefully) correctly formatted request to replace this closed one: 
https://github.com/openmrs/openmrs-module-fhir/pull/159
=> FM-248 support encounter context in observation

api/src/main/java/org/openmrs/module/fhir/api/util/BaseOpenMRSDataUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/ExtensionsUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRAllergyIntoleranceUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIREncounterUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRFamilyMemberHistoryUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRGroupUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRLocationUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRMedicationRequestUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRMedicationUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRObsUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPatientUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPersonUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRRelatedPersonUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRVisitUtil.java
Base extensions are added to the following fields:
- AllergyIntolerance (Allergy)
- Encounter (Encounter, Visit)
- FamiliMemberHistory (Relationship)
- Group (Cohort)
- Location (Location)
- MedicationRequest (DrugOrder)
- Medication (Drug)
- Observation (Obs)
- Patient (Patient)
- Person (Person)
- RelatedPerson (Relationship)
=> SYNCT-211: Create FHIR extensions for BaseOpenmrsData

pom.xml
* Set useSystemClassLoader to false
=> SYNCT-149: Added surefire configuration

.github/PULL_REQUEST_TEMPLATE.md
Proposed a Pull Request Format similar to openmrs-core one.
[see](https://issues.openmrs.org/browse/SYNCT-282)
=> SYNCT-282 Adding a PR template to this repository

api/src/main/java/org/openmrs/module/fhir/api/helper/ClientHelper.java
Added javadoc to ClientHelper interface.
see https://issues.openmrs.org/browse/SYNCT-274
No? Unsure? -> execute command …
=> SYNCT-274 Create extension points that allow implementers control over the sync process through code

README.md
see https://issues.openmrs.org/browse/SYNCT-318
=> SYNCT-318: Added the "requirements" section to readme file

api-2.0/src/test/java/org/openmrs/module/fhir/api/PersonServiceTest.java, api/src/main/java/org/openmrs/module/fhir/api/exceptions/FHIRException.java, api/src/main/java/org/openmrs/module/fhir/api/helper/FHIRClientHelper.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRAddressUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRHumanNameUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPatientUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPersonUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRPractitionerUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRRelatedPersonUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRUtils.java
see https://issues.openmrs.org/browse/SYNCT-246
=> SYNCT-246: Synchronize Person

api-2.0/src/main/java/org/openmrs/module/fhir/helper/ObsHelperImpl2_0.java, api/src/main/java/org/openmrs/module/fhir/api/FHIRHelperService.java, api/src/main/java/org/openmrs/module/fhir/api/constants/ExtensionURL.java, api/src/main/java/org/openmrs/module/fhir/api/impl/FHIRHelperServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/observation/ObservationStrategy.java, api/src/main/java/org/openmrs/module/fhir/api/util/BaseOpenMRSDataUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/ExtensionsUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRConstants.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIREncounterUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRObsUtil.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRUtils.java, api/src/main/java/org/openmrs/module/fhir/api/validator/SpecificObsValidator.java, api/src/main/resources/moduleApplicationContext.xml, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulObservationResourceProvider.java
see 
https://issues.openmrs.org/browse/SYNCT-137
https://issues.openmrs.org/browse/SYNCT-180
=> SYNCT-137: Add Encounters and Obs synchronization

api/src/main/java/org/openmrs/module/fhir/api/util/FHIRVisitUtil.java
see https://issues.openmrs.org/browse/SYNCT-321
=> SYNCT-321: Fixed issue with the visit synchronization

api-2.0/src/test/java/org/openmrs/module/fhir/api/FamilyMemberHistoryServiceTest.java, api/src/main/java/org/openmrs/module/fhir/api/FamilyMemberHistoryService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/FamilyMemberHistoryServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/patient/PatientStrategy.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRFamilyMemberHistoryUtil.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulFamilyMemberHistoryResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRFamilyMemberHistoryResource.java, omod/src/main/java/org/openmrs/module/fhir/swagger/SwaggerDocConstants.java
Issue worked on: https://issues.openmrs.org/browse/GCI-75
=> GCI-75: FHIR project - Rename FamilyHistory with FamilyMemberHistory

.travis.yml
see https://issues.openmrs.org/browse/SYNCT-
No? Unsure? -> execute command `git pull --rebase upstream master`
=> TRAVIS_FIXED: Fixed failing travis builds

api-2.0/src/test/java/org/openmrs/module/fhir/api/RelatedPersonServiceTest.java, api-2.0/src/test/resources/RelatedPersonServiceTest_additionalTestData.xml, api/src/main/java/org/openmrs/module/fhir/api/RelatedPersonService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/RelatedPersonServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/relatedperson/GenericRelatedPersonStrategy.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/relatedperson/RelatedPersonStrategy.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulRelatedPersonProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRRelatedPersonResource.java
* Added the ability to search by patient identifier 
see https://issues.openmrs.org/browse/FM-267
No? Unsure? -> …
=> FM-267: Extend RelatedPerson search api

omod/src/main/java/org/openmrs/module/fhir/filter/AuthorizationFilter.java
I added a validation to send a 401 HTTP error code in case the user is not authenticated to access the resource.
see https://issues.openmrs.org/browse/FM-266
No? -> figure out why and add the fix to your commit. It is your …
=> FM-266: Return 401 instead of 500 when user is unauthenticated

api-2.0/src/test/java/org/openmrs/module/fhir/api/ConditionServiceTest.java, api-2.2/pom.xml, api-2.2/src/main/java/org/openmrs/module/fhir/helper/ConditionHelperImpl2_2.java, api-2.2/src/test/java/org/openmrs/module/fhir/api/ConditionServiceTest.java, api/src/main/java/org/openmrs/module/fhir/api/ConditionService.java, api/src/main/java/org/openmrs/module/fhir/api/helper/ConditionHelper.java, api/src/main/java/org/openmrs/module/fhir/api/impl/ConditionServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/impl/base/BaseConditionHelperImpl.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/condition/ConditionStrategy.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/condition/GenericConditionStrategy.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulConditionResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRConditionResource.java
Add features for users to search for and retrieve one or many Condition resources
- search by uuid
- search by patient
- search by patient identifier
For searchbyUuid works for 1.11.x - 2.4.x but for searchByPatient and searchByPatientIdentifier is only supported from 2.2.x and above. Lower versions are not supported.
see https://issues.openmrs.org/browse/FM-65
No? -> write tests …
=> FM-65: Add features for users to search for and retrieve one or many Condition resources

README.md
Minor fix (subtitle formatting) on line 08
see https://issues.openmrs.org/browse/SYNCT-
There is no previous PR or issue related. There is no break on code
No? -> figure out why and add the fix to your commit. It is your …
=> Minor fix (subtitle formatting) on line 08

api-2.0/src/test/java/org/openmrs/module/fhir/api/ConditionServiceTest.java, api-2.2/src/main/java/org/openmrs/module/fhir/helper/ConditionHelperImpl2_2.java, api-2.2/src/main/java/org/openmrs/module/fhir/util/FHIRConditionUtil2_2.java, api-2.2/src/test/java/org/openmrs/module/fhir/api/ConditionServiceTest.java, api/src/main/java/org/openmrs/module/fhir/api/ConditionService.java, api/src/main/java/org/openmrs/module/fhir/api/helper/ConditionHelper.java, api/src/main/java/org/openmrs/module/fhir/api/impl/ConditionServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/impl/base/BaseConditionHelperImpl.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/condition/ConditionStrategy.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/condition/GenericConditionStrategy.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulConditionResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRConditionResource.java
Added support to update openmrs condition through fhir
https://issues.openmrs.org/browse/FM-69
No? Unsure? -> execute …
=> FM-69: Add support for update OpenMRS Conditions through FHIR

api-2.0/src/test/java/org/openmrs/module/fhir/api/ObsServiceTest.java, api/src/main/java/org/openmrs/module/fhir/api/ObsService.java, api/src/main/java/org/openmrs/module/fhir/api/impl/ObsServiceImpl.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/observation/GenericObservationStrategy.java, api/src/main/java/org/openmrs/module/fhir/api/strategies/observation/ObservationStrategy.java, omod/src/main/java/org/openmrs/module/fhir/providers/RestfulObservationResourceProvider.java, omod/src/main/java/org/openmrs/module/fhir/resources/FHIRObservationResource.java
Search Observation by patient and code(s)
see https://issues.openmrs.org/browse/FM-270
No? Unsure? -> execute command …
=> FM-270: Fix search function for Observation resource to allow search by patient and code

api-1.11/pom.xml, api-1.9/pom.xml, api-2.0/pom.xml, api/pom.xml
I remove Redundant dependencies
see https://issues.openmrs.org/browse/FM-278
No? Unsure? -> execute command `git pull …
=> FM-278: Remove unused dependencies

api/src/main/java/org/openmrs/module/fhir/api/diagnosticreport/handler/RadiologyHandler.java, api/src/main/java/org/openmrs/module/fhir/api/util/FHIRRESTfulGenericClient.java, omod/pom.xml, omod/src/main/java/org/openmrs/module/fhir/server/ConformanceProvider.java, omod/src/main/java/org/openmrs/module/fhir/server/FHIRRESTServer.java, omod/src/main/java/org/openmrs/module/fhir/swagger/SwaggerCodeGenController.java, omod/src/main/java/org/openmrs/module/fhir/swagger/SwaggerSpecificationController.java, omod/src/main/java/org/openmrs/module/fhir/swagger/SwaggerSpecificationCreator.java, omod/src/test/java/org/openmrs/module/fhir/omod/SwaggerDocumentGenerationTestCase.java, omod/src/test/java/org/openmrs/module/fhir/omod/SwaggerSDKGenerationTestCase.java, pom.xml
Updates the FHIR module to use HAPI FHIR 4.0.3 (up from 2.5)
see https://issues.openmrs.org/browse/FM-279
=> FM-279: update to HAPI FHIR 4.0.3

api-2.0/src/test/java/org/openmrs/module/fhir/api/ObsServiceTest.java, api-2.0/src/test/resources/Concept_customTestData.xml, api/src/main/java/org/openmrs/module/fhir/api/strategies/observation/ObservationStrategy.java
Fix search observation by patient and concept uuid
see https://issues.openmrs.org/browse/FM-277
No? Unsure? -> execute …
=> FIX-277: Fixing search by patient and concept Uuid
